name: Delete workflow history

on:
  workflow_call:
    inputs:
      workflow:
        description: workflow-id, workflow-name or filename
        required: true
        type: string
    secrets:
      github_token:
        required: false

jobs:
  delete:
    runs-on: ubuntu@latest
    timeout-minutes: 1
    env:
      GH_TOKEN: ${{ secrets.github_token || github.token }}
      REPOSITORY: ${{ github.repository }}
      WORKFLOW: ${{ inputs.workflow }}
    steps:
      - run: gh workflow view "${WORKFLOW}"
      - run: |
          gh run list --workflow "${WORKFLOW}" --limit 1000 --json databaseId,status --jq '.[] | select(.status == "completed") | .databaseId' \
            | xargs -n 1 -I {} gh api -X DELETE repos/${REPOSITORY}/actions/runs/{}
