name: Release
# Release action with changesets

on:
  push:
    branches:
      - main
    paths:
      - .changeset

concurrency: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node and restore packages
        uses: ./.github/actions/setup-node-and-pnpm-then-restore-packages
      - name: Setup npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            registry=https://registry.npmjs.org/
            always-auth=true
          EOF
      # GitHub Packages
      # - name: Setup npmrc
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     cat << EOF > "$HOME/.npmrc"
      #       //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
      #       @x7ddf74479jn5:registry=https://npm.pkg.github.com/
      #     EOF
      - name: Create release PR or publish to GitHub Packages
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          publish: pnpm ci:publish
          title: "📦 release: version packages"
          commit: "📦 release: version packages"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
